import TopBar from '@/components/Layout/TopBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Layout/SideBar'
import { Toaster } from '@/components/ui/toaster'
import Providers from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex flex-col min-h-screen">

        <TopBar />

        <div className="flex">
          <Providers>
            <Sidebar />
          </Providers>
          <div className="bg-white px-6 py-6 w-full">
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
